### ISSUE TITLE
Setting `do-not-disturb off` does not reflect dnd mode being off in the menubar

### ISSUE THREAD

**Issue by megalithic** [sindresorhus/do-not-disturb-cli#1]
Using newly installed instance of 10.14 (Mojave) with `do-not-disturb-cli` v0.2.0 installed, `do-not disturb off` after previously setting `do-not-disturb on` does not seem to update the menubar icon to reflect that dnd mode is now off. I'm not sure if it actually is still on or not. It may just be that the icon isn't updating properly. Will work on verifying that.

At any rate, just wanted to file this issue in the event that others are experiencing this.

**Comment by silviogutierrez** [comment]
I can replicate this. Only seems to affect off.

To reproduce:

1. Turn on DND *manually*
2. Call this command with off.
3. Note that `node_modules/.bin/do-not-disturb` will report off.
4. Verify the icon is still on.
5. Run `osascript -e 'display notification "hello world!"'`
6. You will see no notification.
7. Turn off manually.
8. Repeat 5, you'll see notification.

So two issues: icon won't update, *and* the tool will think it's off. The icon is the source of truth apparently.

Some good news though: if you turn it *on* through the CLI, then you can turn it off through the CLI and the icon will update.

So if you want to be super safe, always turn on in the CLI even if it's already on. Then off will work.

@megalithic : not sure why you closed this.

@sindresorhus : thanks for making this. I wish I could help more, but know zero swift.
